/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as DashboardDashboardLayoutRouteImport } from './routes/dashboard/_dashboardLayout'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthProviderRedirectRouteImport } from './routes/_auth/provider-redirect'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardDashboardLayoutIndexRouteImport } from './routes/dashboard/_dashboardLayout.index'
import { Route as DashboardDashboardLayoutSummaryIndexRouteImport } from './routes/dashboard/_dashboardLayout.summary/index'
import { Route as DashboardDashboardLayoutSheetsIndexRouteImport } from './routes/dashboard/_dashboardLayout.sheets/index'
import { Route as DashboardDashboardLayoutSettingsIndexRouteImport } from './routes/dashboard/_dashboardLayout.settings/index'
import { Route as DashboardDashboardLayoutIntegrationsIndexRouteImport } from './routes/dashboard/_dashboardLayout.integrations/index'
import { Route as DashboardDashboardLayoutCommitsIndexRouteImport } from './routes/dashboard/_dashboardLayout.commits/index'
import { Route as DashboardDashboardLayoutSheetsSettingsRouteImport } from './routes/dashboard/_dashboardLayout.sheets/settings'
import { Route as DashboardDashboardLayoutSheetsCreateRouteImport } from './routes/dashboard/_dashboardLayout.sheets/create'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DashboardDashboardLayoutRoute =
  DashboardDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderRedirectRoute = AuthProviderRedirectRouteImport.update({
  id: '/_auth/provider-redirect',
  path: '/provider-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardLayoutIndexRoute =
  DashboardDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutSummaryIndexRoute =
  DashboardDashboardLayoutSummaryIndexRouteImport.update({
    id: '/summary/',
    path: '/summary/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutSheetsIndexRoute =
  DashboardDashboardLayoutSheetsIndexRouteImport.update({
    id: '/sheets/',
    path: '/sheets/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutSettingsIndexRoute =
  DashboardDashboardLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutIntegrationsIndexRoute =
  DashboardDashboardLayoutIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutCommitsIndexRoute =
  DashboardDashboardLayoutCommitsIndexRouteImport.update({
    id: '/commits/',
    path: '/commits/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutSheetsSettingsRoute =
  DashboardDashboardLayoutSheetsSettingsRouteImport.update({
    id: '/sheets/settings',
    path: '/sheets/settings',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)
const DashboardDashboardLayoutSheetsCreateRoute =
  DashboardDashboardLayoutSheetsCreateRouteImport.update({
    id: '/sheets/create',
    path: '/sheets/create',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/provider-redirect': typeof AuthProviderRedirectRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/dashboard/': typeof DashboardDashboardLayoutIndexRoute
  '/dashboard/sheets/create': typeof DashboardDashboardLayoutSheetsCreateRoute
  '/dashboard/sheets/settings': typeof DashboardDashboardLayoutSheetsSettingsRoute
  '/dashboard/commits': typeof DashboardDashboardLayoutCommitsIndexRoute
  '/dashboard/integrations': typeof DashboardDashboardLayoutIntegrationsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardLayoutSettingsIndexRoute
  '/dashboard/sheets': typeof DashboardDashboardLayoutSheetsIndexRoute
  '/dashboard/summary': typeof DashboardDashboardLayoutSummaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/provider-redirect': typeof AuthProviderRedirectRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardLayoutIndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/dashboard/sheets/create': typeof DashboardDashboardLayoutSheetsCreateRoute
  '/dashboard/sheets/settings': typeof DashboardDashboardLayoutSheetsSettingsRoute
  '/dashboard/commits': typeof DashboardDashboardLayoutCommitsIndexRoute
  '/dashboard/integrations': typeof DashboardDashboardLayoutIntegrationsIndexRoute
  '/dashboard/settings': typeof DashboardDashboardLayoutSettingsIndexRoute
  '/dashboard/sheets': typeof DashboardDashboardLayoutSheetsIndexRoute
  '/dashboard/summary': typeof DashboardDashboardLayoutSummaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/provider-redirect': typeof AuthProviderRedirectRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/dashboard/_dashboardLayout/': typeof DashboardDashboardLayoutIndexRoute
  '/dashboard/_dashboardLayout/sheets/create': typeof DashboardDashboardLayoutSheetsCreateRoute
  '/dashboard/_dashboardLayout/sheets/settings': typeof DashboardDashboardLayoutSheetsSettingsRoute
  '/dashboard/_dashboardLayout/commits/': typeof DashboardDashboardLayoutCommitsIndexRoute
  '/dashboard/_dashboardLayout/integrations/': typeof DashboardDashboardLayoutIntegrationsIndexRoute
  '/dashboard/_dashboardLayout/settings/': typeof DashboardDashboardLayoutSettingsIndexRoute
  '/dashboard/_dashboardLayout/sheets/': typeof DashboardDashboardLayoutSheetsIndexRoute
  '/dashboard/_dashboardLayout/summary/': typeof DashboardDashboardLayoutSummaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/login'
    | '/provider-redirect'
    | '/register'
    | '/dashboard'
    | '/posts/$postId'
    | '/posts/'
    | '/dashboard/'
    | '/dashboard/sheets/create'
    | '/dashboard/sheets/settings'
    | '/dashboard/commits'
    | '/dashboard/integrations'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/dashboard/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/provider-redirect'
    | '/register'
    | '/dashboard'
    | '/posts/$postId'
    | '/posts'
    | '/dashboard/sheets/create'
    | '/dashboard/sheets/settings'
    | '/dashboard/commits'
    | '/dashboard/integrations'
    | '/dashboard/settings'
    | '/dashboard/sheets'
    | '/dashboard/summary'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/_pathlessLayout'
    | '/_auth/login'
    | '/_auth/provider-redirect'
    | '/_auth/register'
    | '/dashboard'
    | '/dashboard/_dashboardLayout'
    | '/posts/$postId'
    | '/posts/'
    | '/dashboard/_dashboardLayout/'
    | '/dashboard/_dashboardLayout/sheets/create'
    | '/dashboard/_dashboardLayout/sheets/settings'
    | '/dashboard/_dashboardLayout/commits/'
    | '/dashboard/_dashboardLayout/integrations/'
    | '/dashboard/_dashboardLayout/settings/'
    | '/dashboard/_dashboardLayout/sheets/'
    | '/dashboard/_dashboardLayout/summary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProviderRedirectRoute: typeof AuthProviderRedirectRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/provider-redirect': {
      id: '/_auth/provider-redirect'
      path: '/provider-redirect'
      fullPath: '/provider-redirect'
      preLoaderRoute: typeof AuthProviderRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashboardLayout/': {
      id: '/dashboard/_dashboardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/summary/': {
      id: '/dashboard/_dashboardLayout/summary/'
      path: '/summary'
      fullPath: '/dashboard/summary'
      preLoaderRoute: typeof DashboardDashboardLayoutSummaryIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/sheets/': {
      id: '/dashboard/_dashboardLayout/sheets/'
      path: '/sheets'
      fullPath: '/dashboard/sheets'
      preLoaderRoute: typeof DashboardDashboardLayoutSheetsIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/settings/': {
      id: '/dashboard/_dashboardLayout/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/integrations/': {
      id: '/dashboard/_dashboardLayout/integrations/'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardDashboardLayoutIntegrationsIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/commits/': {
      id: '/dashboard/_dashboardLayout/commits/'
      path: '/commits'
      fullPath: '/dashboard/commits'
      preLoaderRoute: typeof DashboardDashboardLayoutCommitsIndexRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/sheets/settings': {
      id: '/dashboard/_dashboardLayout/sheets/settings'
      path: '/sheets/settings'
      fullPath: '/dashboard/sheets/settings'
      preLoaderRoute: typeof DashboardDashboardLayoutSheetsSettingsRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
    '/dashboard/_dashboardLayout/sheets/create': {
      id: '/dashboard/_dashboardLayout/sheets/create'
      path: '/sheets/create'
      fullPath: '/dashboard/sheets/create'
      preLoaderRoute: typeof DashboardDashboardLayoutSheetsCreateRouteImport
      parentRoute: typeof DashboardDashboardLayoutRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface DashboardDashboardLayoutRouteChildren {
  DashboardDashboardLayoutIndexRoute: typeof DashboardDashboardLayoutIndexRoute
  DashboardDashboardLayoutSheetsCreateRoute: typeof DashboardDashboardLayoutSheetsCreateRoute
  DashboardDashboardLayoutSheetsSettingsRoute: typeof DashboardDashboardLayoutSheetsSettingsRoute
  DashboardDashboardLayoutCommitsIndexRoute: typeof DashboardDashboardLayoutCommitsIndexRoute
  DashboardDashboardLayoutIntegrationsIndexRoute: typeof DashboardDashboardLayoutIntegrationsIndexRoute
  DashboardDashboardLayoutSettingsIndexRoute: typeof DashboardDashboardLayoutSettingsIndexRoute
  DashboardDashboardLayoutSheetsIndexRoute: typeof DashboardDashboardLayoutSheetsIndexRoute
  DashboardDashboardLayoutSummaryIndexRoute: typeof DashboardDashboardLayoutSummaryIndexRoute
}

const DashboardDashboardLayoutRouteChildren: DashboardDashboardLayoutRouteChildren =
  {
    DashboardDashboardLayoutIndexRoute: DashboardDashboardLayoutIndexRoute,
    DashboardDashboardLayoutSheetsCreateRoute:
      DashboardDashboardLayoutSheetsCreateRoute,
    DashboardDashboardLayoutSheetsSettingsRoute:
      DashboardDashboardLayoutSheetsSettingsRoute,
    DashboardDashboardLayoutCommitsIndexRoute:
      DashboardDashboardLayoutCommitsIndexRoute,
    DashboardDashboardLayoutIntegrationsIndexRoute:
      DashboardDashboardLayoutIntegrationsIndexRoute,
    DashboardDashboardLayoutSettingsIndexRoute:
      DashboardDashboardLayoutSettingsIndexRoute,
    DashboardDashboardLayoutSheetsIndexRoute:
      DashboardDashboardLayoutSheetsIndexRoute,
    DashboardDashboardLayoutSummaryIndexRoute:
      DashboardDashboardLayoutSummaryIndexRoute,
  }

const DashboardDashboardLayoutRouteWithChildren =
  DashboardDashboardLayoutRoute._addFileChildren(
    DashboardDashboardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProviderRedirectRoute: AuthProviderRedirectRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
